### ISSUE TITLE
advice on semantic segmentation

### ISSUE THREAD

**Issue by rusty-electron** [NickLucche/pyramid-cnn-leaves-segmentation#2]
Thanks @NickLucche for this code implementation in torch. I ran your code and it works fine.

I will be very grateful if you can give me some advice on how I might be able to extract the largest 1-2 leaves from an image such as this one using traditional image processing or DL methods.

![image](https://user-images.githubusercontent.com/22986666/115552189-a678e880-a2c9-11eb-8774-c490a6f7e51c.png)

I wish to have selection such as these as depicted in the source paper:

![image](https://user-images.githubusercontent.com/22986666/115552663-2f901f80-a2ca-11eb-837a-37cf636399b3.png)

My final goal is the get a resulting image such as these:

![image](https://user-images.githubusercontent.com/22986666/115553293-df658d00-a2ca-11eb-8ea4-a9b705e03727.png) ![image](https://user-images.githubusercontent.com/22986666/115553248-d1b00780-a2ca-11eb-8518-1a74d67e3620.png)

I have tried other segmentation networks available in github but they are generally trained on datasets with outdoor backgrounds so I haven't been able to get good results.

**Comment by NickLucche** [comment]
Hey @rusty-electron, sorry for the late reply.
I think what you're looking into can be achieved with a combinations of some basic cv2 functions like:
`
cont1, _ = cv2.findContours(image, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)
cont1 = sorted(cont1, key=cv2.contourArea, reverse=True)
 `
From there on you can select the top 2 leaves based on their area. 
You can combine that with the output of the network and a couple more functions like `dilation` to make sure edges are connected.

If I recall correctly on the specific subject, I think this paper [Leaf recognition using contour based edge detection and SIFT algorithm
](https://ieeexplore.ieee.org/document/7238345) was doing something very simple along those lines, maybe you can take a look at that.
